<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		<div class="col-md-6 offset-md-3">
			
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<form method="get" action="/quem_seguir">
								<div class="input-group mb-3">
									<input type="text" name="pesquisarPor" class="form-control" placeholder="Quem você está procurando?">
									<div class="input-group-append">
										<button class="btn btn-primary" type="submit">Procurar</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>

			<?php foreach($this->view->usuarios as $indice_arr => $usuario) { ?>
				<div class="row mb-2">
					<div class="col">
						<div class="card">
							<div class="card-body">
								<div class="row">
									<div class="col-md-6">
										<?= $usuario['nome'] ?>
									</div>
								
									<div class="col-md-6 d-flex justify-content-end">
										<div>
											<?php if($usuario['seguindo_sn'] == 0) { ?>
												<a href="/acao?acao=seguir&id_usuario=<?=$usuario['id']?>" class="btn btn-success">Seguir</a>
											<?php } ?>

											<?php if($usuario['seguindo_sn'] == 1) { ?>
												<a href="/acao?acao=deixar_de_seguir&id_usuario=<?=$usuario['id']?>" class="btn btn-danger">Deixar de seguir</a>
											<?php } ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			<?php } ?>
		</div>
	</div>
</div>